# Generated by Django 4.1.2 on 2022-10-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_myauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='myauthor',
        ),
    ]
