# Generated by Django 4.1.2 on 2022-10-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_post_myauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
    ]
